#include "../src/read_input.cpp"
#include "../src/wing_geometry.cpp"
#include "../src/write_output.cpp"
#include "../src/induced_velocity.cpp"
#include "../src/gauss.cpp"
#include "../src/wake_geometry.cpp"
#include "../src/equ_system.cpp"
#include "../src/lift_force.cpp"
#include "../src/drag_force.cpp"
#include "../src/PitchMoment.cpp"
#include "../src/longtrim.cpp"

